spring:
  application:
    name: project

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
      generate_statistics: true

  datasource:
    url: jdbc:postgresql://c5flugvup2318r.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com/de374u421n0ght
    username: u1hfcjp3fe6vjq
    password: pef84797338617df46f5e0afb005cf0e92415ee7037732af053f2041e26ea0f41
    driver-class-name: org.postgresql.Driver

#  datasource:
#    url: jdbc:postgresql://localhost:5432/project_db
#    username: songheesu
#    password: 10040160
#    driver-class-name: org.postgresql.Driver
